# Generated by Django 6.0.6 on 2026-06-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text='URL için benzersiz isim (örn: geometrik-metal-tablo)', unique=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(verbose_name='Ürün Açıklaması')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Normal Fiyat')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirimli Fiyat')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok Adeti')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Ana Görsel (Sitede görünecek ilk resim)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sitede Yayınlansın mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
