# Generated by Django 6.0.6 on 2026-06-17 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Ürün Videosu (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL için benzersiz isim', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='İndirimli Başlangıç Fiyatı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(upload_to='products/main/', verbose_name='Ana Görsel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Başlangıç Fiyatı (En Küçük Boyut)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Toplam Stok Adeti'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Galeri Görseli')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Fotoğrafı',
                'verbose_name_plural': 'Ürün Fotoğrafları',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Örn: 50x70 cm, 100x150 cm', max_length=50, verbose_name='Boyut / Ölçü')),
                ('price_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fiyat Farkı (+ TL)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Boyut Varyasyonu',
                'verbose_name_plural': 'Ürün Boyut Varyasyonları',
            },
        ),
    ]
