# Generated by Django 6.0.6 on 2026-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_features',
            field=models.TextField(blank=True, null=True, verbose_name='2. Açıklama (Kutulara Gidecek Kurumsal Metin)'),
        ),
    ]
