# Generated by Django 6.0.6 on 2026-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Payment'), ('Paid', 'Paid (Preparing Product)'), ('Shipped', 'Shipped (On the Way)'), ('Completed', 'Delivered & Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
