# Generated by Django 5.0.13 on 2026-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="Müşterilerin Google'da bulması için virgülle ayırarak etiketleri yaz kanka. Örn: metal tablo, metal wall art, geyik figürü", max_length=500, null=True, verbose_name='SEO Anahtar Kelimeler'),
        ),
    ]
