# Generated by Django 5.0.13 on 2026-06-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SEO Anahtar Kelimeler'),
        ),
    ]
